version: '3.0'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanobot
    image: nanobot
    restart: unless-stopped
    volumes:
      -  $PWD:/nanobot
    env_file:
      - .env
#   environment:
