version: "3.0"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanobot
    image: nanobot
    restart: unless-stopped
    volumes:
      - ./:/nanobot:Z
    env_file:
      - .env
#   environment:
