
class insult_list():
    list = [
        "fuck you",
        "eat shit",
        "kill yourself NOW",
        "placeholder insult because fuck you",
        "faggot frog",
        "turkish",
        "french hippie faggot HON HON HON",
        "canada is not a real country",
        "eat my nuts you sad sack of shit",
        "go fuck yourself",
        "get off discord and go outside",
        "Where's your tomboy tradwife, huh?",
        "You're being more faggoty then ctaetcsh rn",
        "Are you ran because your computer is shit",
        "AyyMD lives rent free in your head",
        "You are now manually blinking",
        "You are now manually breathing",
        "dry lip having mf DONT LICK THEM FAGGOT",
        "so down bad you give discord money every month",
        "if furries want to be animals then my hunting license is valid",
        "NQN fucking sucks",
        "you probably use reddit",
        "you probably use twitter",
        "you probably use epic games store",
        "stop being a vrchat faggot",
        "you will never be a woman",
        "tranny",
        "you will wake up with furries in your bed tomorrow morning",
        "you probably unironically use gentoo",
        "you probably use NQN image search for porn"
    ]
